"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

# 🚨 VERIFICACIÓN DE VERSIÓN - DEBE APARECER EN LOGS
print("🚨🚨🚨 SETTINGS.PY VERSIÓN 2025-10-05 10:46 🚨🚨🚨")
print("🚨🚨🚨 SI VES ESTO, AZURE ESTÁ USANDO EL CÓDIGO CORRECTO 🚨🚨🚨")

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-xtffuwi4x#$sy+@d0(5rzmk)0#s%1nmdwx*o-3(wcntm7yg54('

# SECURITY WARNING: don't run with debug turned on in production!
# Temporalmente habilitado para diagnóstico
import os
DEBUG = True if 'WEBSITE_HOSTNAME' in os.environ else True

ALLOWED_HOSTS = [
    'rober-djangowebapp-babgd9bkfybugqfd.francecentral-01.azurewebsites.net',
    'rober-djangowebapp-babgd9bkfybugqfd.azurewebsites.net',
    '169.254.129.3',  # IP interna de Azure
    '169.254.129.5',  # Nueva IP interna de Azure
    'localhost',
    '127.0.0.1',
    '*',  # TEMPORAL: permitir todos los hosts
]

# Log de diagnóstico
if 'WEBSITE_HOSTNAME' in os.environ:
    print("=== AZURE DEBUG INFO ===")
    print(f"WEBSITE_HOSTNAME: {os.environ.get('WEBSITE_HOSTNAME')}")
    print(f"DEBUG: {DEBUG}")
    print(f"ALLOWED_HOSTS: {ALLOWED_HOSTS}")
    print("=========================")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'relecloud.apps.RelecloudConfig',
    'crispy_forms',
    'crispy_bootstrap4',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'djangodbprod',  # Tu base de datos en Azure
        'USER': 'rober',         # Tu usuario
        'PASSWORD': 'COMEmasPOLLO1',  # Tu contraseña
        'HOST': 'djangowebdbpostgre.postgres.database.azure.com',  # Tu servidor Azure
        'PORT': '5432',
        'OPTIONS': {
            'sslmode': 'require',  # Importante para Azure
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Configuración de archivos estáticos para Azure
print("🚨🚨🚨 SETTINGS.PY VERSIÓN 2025-10-05 10:47 CORREGIDO 🚨🚨🚨")
if 'WEBSITE_HOSTNAME' in os.environ:  # Detectar Azure
    print("Configurando middleware para Azure...")
    # Configuración de WhiteNoise para Azure
    MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'whitenoise.middleware.WhiteNoiseMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ]
    
    # Configuración de almacenamiento estático para Azure
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    
    # Configuración CSRF para Azure
    CSRF_TRUSTED_ORIGINS = [
        'https://rober-djangowebapp-babgd9bkfybugqfd.francecentral-01.azurewebsites.net'
    ]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Crispy Forms
CRISPY_TEMPLATE_PACK = 'bootstrap4'

# =============================================================================
# CONFIGURACIÓN ESPECÍFICA PARA AZURE (Detección automática)
# =============================================================================
if 'WEBSITE_HOSTNAME' in os.environ:
    print("🔥 CONFIGURANDO PARA AZURE 🔥")
    
    # Override middleware para Azure
    MIDDLEWARE = [
        'relecloud.middleware.AzureDebugMiddleware',  # TEMPORAL: Debug middleware primero
        'django.middleware.security.SecurityMiddleware',
        'whitenoise.middleware.WhiteNoiseMiddleware',  # Para servir archivos estáticos
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ]
    
    # Configuración de almacenamiento estático para Azure
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    
    # Configuración CSRF para Azure
    CSRF_TRUSTED_ORIGINS = [
        'https://rober-djangowebapp-babgd9bkfybugqfd.francecentral-01.azurewebsites.net',
    ]
    
    # Logging para Azure
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'handlers': {
            'console': {
                'class': 'logging.StreamHandler',
            },
        },
        'root': {
            'handlers': ['console'],
        },
        'loggers': {
            'django': {
                'handlers': ['console'],
                'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
                'propagate': False,
            },
        },
    }
    
    print("🔥 CONFIGURACIÓN AZURE COMPLETADA 🔥")
