# Generated by Django 5.2.7 on 2025-10-01 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relecloud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destinaton',
            new_name='Destination',
        ),
    ]
